import type { Episode } from './types';

/**
 * Contenu de démonstration — 6 épisodes.
 *
 * Les entreprises et les invités sont fictifs. Les ressources citées pointent
 * en revanche vers des sources réelles, pour que les blocs « Les liens de
 * l'épisode » se comportent comme en production.
 *
 * Ajouter un épisode = ajouter un objet dans ce tableau. Rien d'autre.
 * L'ordre n'a pas d'importance : le tri se fait sur `publishedAt`.
 */

const AUDIO = '/audio/dlm-demo.wav';

export const episodes: Episode[] = [
  {
    id: 'ep-01',
    slug: 'helio-industries',
    aliases: ['helio'],
    episodeNumber: 1,
    title: 'Décarboner une usine sans arrêter la ligne',
    excerpt:
      'Helio Industries produit des échangeurs thermiques depuis 1974. Marc Vandenberghe a engagé la conversion de ses quatre fours sans jamais interrompre la production.',
    description: [
      'Il y a deux façons de rater une transition industrielle : la reporter jusqu’à ce qu’elle soit imposée, ou l’engager si vite qu’on casse l’outil. Marc Vandenberghe a cherché la troisième — avancer four par four, campagne par campagne, en gardant les carnets de commandes remplis.',
      'Nous avons enregistré dans le bureau d’études, porte ouverte sur l’atelier. On entend les presses. C’était le point : parler de décarbonation à l’endroit exact où elle coûte quelque chose.',
      'Il raconte les arbitrages qu’on ne met pas dans les communiqués — le premier four converti qui tourne moins bien que l’ancien, les six mois où l’équipe de nuit n’y croit pas, le client allemand qui devient l’allié inattendu du projet.',
    ],
    publishedAt: '2026-03-18',
    duration: 3247,
    recordedAt: 'Sélestat, Bas-Rhin',
    topics: ['Industrie', 'Transformation'],
    guest: {
      name: 'Marc Vandenberghe',
      role: 'Président',
      company: 'Helio Industries',
      bio: 'Ingénieur thermicien de formation, il reprend l’entreprise familiale en 2011. Cinq ans plus tard, il engage un plan de conversion énergétique de l’ensemble du site de Sélestat — 180 salariés, quatre lignes.',
      linkedin: 'https://www.linkedin.com/',
      website: 'https://www.helio-industries.fr',
      portrait: {
        src: '/episodes/helio-industries-portrait.jpg',
        alt: 'Marc Vandenberghe, président d’Helio Industries, dans le bureau d’études du site de Sélestat.',
        width: 1400,
        height: 1750,
      },
    },
    coverImage: {
      src: '/episodes/helio-industries-portrait.jpg',
      alt: 'Marc Vandenberghe, président d’Helio Industries, dans le bureau d’études du site de Sélestat.',
      width: 1400,
      height: 1750,
    },
    environmentImage: {
      src: '/episodes/env-atelier.jpg',
      alt: 'Plans techniques et prototypes sur une table du bureau d’études d’Helio Industries.',
      width: 1800,
      height: 1200,
    },
    audioUrl: AUDIO,
    audioBytes: 1280044,
    youtubeId: 'dQw4w9WgXcQ',
    clientUrl: 'https://www.helio-industries.fr',
    platforms: {
      spotify: 'https://open.spotify.com/show/derriere-la-marque',
      apple: 'https://podcasts.apple.com/fr/podcast/derriere-la-marque',
      youtube: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      deezer: 'https://www.deezer.com/fr/show/derriere-la-marque',
      amazon: 'https://music.amazon.fr/podcasts/derriere-la-marque',
    },
    resources: [
      {
        title: 'Décarbonation de l’industrie — dispositifs et retours d’expérience',
        url: 'https://www.ademe.fr/',
        category: 'Étude',
        source: 'ADEME',
        description:
          'La documentation citée par Marc quand il évoque le financement des deux premières campagnes.',
      },
      {
        title: 'France Industrie — chiffres de l’industrie française',
        url: 'https://www.franceindustrie.org/',
        category: 'Référence',
        source: 'France Industrie',
      },
      {
        title: 'Les aides Bpifrance à la transition écologique',
        url: 'https://www.bpifrance.fr/',
        category: 'Référence',
        source: 'Bpifrance',
      },
      {
        title: 'Helio Industries',
        url: 'https://www.helio-industries.fr',
        category: 'Entreprise',
        source: 'Site du client',
      },
      {
        title: 'Les coulisses de l’enregistrement à Sélestat',
        url: 'https://www.youtube.com/@derrierelamarque',
        category: 'Coulisses',
        source: 'Derrière la marque',
        image: '/episodes/env-atelier.jpg',
      },
    ],
  },

  {
    id: 'ep-02',
    slug: 'atelier-brut',
    aliases: ['brut'],
    episodeNumber: 2,
    title: 'Fabriquer lentement dans un marché qui va vite',
    excerpt:
      'Sofiane Belkacem refuse les délais de six semaines. Son atelier de mobilier annonce huit mois d’attente — et n’a jamais eu autant de commandes.',
    description: [
      'Atelier Brut fabrique une centaine de pièces par an. Massif, assemblages visibles, finitions à l’huile. Sofiane Belkacem a longtemps essayé de suivre le rythme du marché, avant de faire l’inverse : allonger les délais, augmenter les prix, réduire le catalogue.',
      'Enregistré dans l’atelier, entre la scie à format et le stock de chêne. On parle de gestes, de séchage, de bois qui travaille — et très concrètement d’économie : ce que coûte la lenteur, et ce qu’elle rapporte.',
      'Un épisode sur une question que beaucoup de marques se posent sans oser la formuler : à quel moment la contrainte de production devient-elle le récit de la marque ?',
    ],
    publishedAt: '2026-04-15',
    duration: 2986,
    recordedAt: 'Angers, Maine-et-Loire',
    topics: ['Design', 'Fabrication'],
    guest: {
      name: 'Sofiane Belkacem',
      role: 'Fondateur',
      company: 'Atelier Brut',
      bio: 'Ébéniste formé aux Compagnons du Devoir, il ouvre Atelier Brut en 2017. Neuf personnes aujourd’hui, une centaine de pièces par an, aucune sous-traitance.',
      linkedin: 'https://www.linkedin.com/',
      website: 'https://www.atelier-brut.fr',
      portrait: {
        src: '/episodes/atelier-brut-portrait.jpg',
        alt: 'Sofiane Belkacem, fondateur d’Atelier Brut, devant le mur de bois de son atelier d’Angers.',
        width: 1400,
        height: 1750,
      },
    },
    coverImage: {
      src: '/episodes/atelier-brut-portrait.jpg',
      alt: 'Sofiane Belkacem, fondateur d’Atelier Brut, devant le mur de bois de son atelier d’Angers.',
      width: 1400,
      height: 1750,
    },
    environmentImage: {
      src: '/episodes/env-atelier.jpg',
      alt: 'Établi, plans et outils dans l’atelier d’Atelier Brut à Angers.',
      width: 1800,
      height: 1200,
    },
    audioUrl: AUDIO,
    audioBytes: 1280044,
    youtubeId: 'dQw4w9WgXcQ',
    clientUrl: 'https://www.atelier-brut.fr',
    platforms: {
      spotify: 'https://open.spotify.com/show/derriere-la-marque',
      apple: 'https://podcasts.apple.com/fr/podcast/derriere-la-marque',
      youtube: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      deezer: 'https://www.deezer.com/fr/show/derriere-la-marque',
    },
    resources: [
      {
        title: 'Mobilier National — collections et savoir-faire',
        url: 'https://www.mobiliernational.culture.gouv.fr/',
        category: 'Référence',
        source: 'Mobilier National',
      },
      {
        title: 'Cité du design — Saint-Étienne',
        url: 'https://www.citedudesign.com/',
        category: 'Design',
        source: 'Cité du design',
      },
      {
        title: 'Vitra — histoire des collections et de la production',
        url: 'https://www.vitra.com/',
        category: 'Marque',
        source: 'Vitra',
        description: 'La référence que Sofiane cite pour parler d’industrialisation réussie.',
      },
      {
        title: 'Musée des Arts Décoratifs',
        url: 'https://madparis.fr/',
        category: 'Référence',
        source: 'MAD Paris',
      },
      {
        title: 'Atelier Brut',
        url: 'https://www.atelier-brut.fr',
        category: 'Entreprise',
        source: 'Site du client',
      },
    ],
  },

  {
    id: 'ep-03',
    slug: 'maison-verrier',
    aliases: ['verrier'],
    episodeNumber: 3,
    title: 'Faut-il encore ouvrir des magasins ?',
    excerpt:
      'Camille Aubert a fermé quatre boutiques et en a ouvert deux. Elle explique pourquoi ce n’est pas un plan de réduction, mais un changement de fonction.',
    description: [
      'Maison Verrier vend de la porcelaine depuis 1908. En 2023, l’enseigne compte onze boutiques dont la moitié ne gagne plus d’argent. La réponse évidente était de tout basculer en ligne. Camille Aubert a fait autre chose.',
      'Nous avons enregistré dans la boutique du centre-ville, avant l’ouverture. Elle décrit une bascule simple à énoncer et difficile à exécuter : arrêter d’évaluer un magasin sur son chiffre d’affaires propre, et commencer à le mesurer sur ce qu’il déclenche ailleurs.',
      'Elle donne les chiffres, les résistances internes, et le moment précis où le comité de direction a accepté de changer d’indicateur.',
    ],
    publishedAt: '2026-05-20',
    duration: 3410,
    recordedAt: 'Limoges, Haute-Vienne',
    topics: ['Retail', 'Marque'],
    guest: {
      name: 'Camille Aubert',
      role: 'Directrice générale',
      company: 'Maison Verrier',
      bio: 'Passée par la distribution spécialisée et l’e-commerce, elle prend la direction générale de Maison Verrier en 2022. Elle y conduit la refonte du réseau de boutiques et du modèle de marque.',
      linkedin: 'https://www.linkedin.com/',
      website: 'https://www.maison-verrier.fr',
      portrait: {
        src: '/episodes/maison-verrier-portrait.jpg',
        alt: 'Camille Aubert, directrice générale de Maison Verrier, dans les bureaux de Limoges.',
        width: 1400,
        height: 1750,
      },
    },
    coverImage: {
      src: '/episodes/maison-verrier-portrait.jpg',
      alt: 'Camille Aubert, directrice générale de Maison Verrier, dans les bureaux de Limoges.',
      width: 1400,
      height: 1750,
    },
    environmentImage: {
      src: '/episodes/env-retail.jpg',
      alt: 'Intérieur de la boutique Maison Verrier avant l’ouverture, à Limoges.',
      width: 1800,
      height: 1200,
    },
    audioUrl: AUDIO,
    audioBytes: 1280044,
    youtubeId: 'dQw4w9WgXcQ',
    clientUrl: 'https://www.maison-verrier.fr',
    platforms: {
      spotify: 'https://open.spotify.com/show/derriere-la-marque',
      apple: 'https://podcasts.apple.com/fr/podcast/derriere-la-marque',
      youtube: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      deezer: 'https://www.deezer.com/fr/show/derriere-la-marque',
      amazon: 'https://music.amazon.fr/podcasts/derriere-la-marque',
      castbox: 'https://castbox.fm/channel/derriere-la-marque',
    },
    resources: [
      {
        title: 'Chiffres clés du commerce et de l’e-commerce en France',
        url: 'https://www.fevad.com/',
        category: 'Étude',
        source: 'Fevad',
        description: 'Les données de fréquentation citées à la moitié de l’épisode.',
      },
      {
        title: 'Commerce de détail — séries longues',
        url: 'https://www.insee.fr/',
        category: 'Étude',
        source: 'Insee',
      },
      {
        title: 'Institut Français de la Mode — observatoire de la consommation',
        url: 'https://www.ifmparis.fr/',
        category: 'Étude',
        source: 'IFM',
      },
      {
        title: 'LSA — actualité du commerce et de la distribution',
        url: 'https://www.lsa-conso.fr/',
        category: 'Article',
        source: 'LSA',
        description: 'La presse professionnelle que Camille cite sur les ouvertures de 2025.',
      },
      {
        title: 'Maison Verrier',
        url: 'https://www.maison-verrier.fr',
        category: 'Entreprise',
        source: 'Site du client',
      },
      {
        title: 'La boutique de Limoges, une heure avant l’ouverture',
        url: 'https://www.youtube.com/@derrierelamarque',
        category: 'Coulisses',
        source: 'Derrière la marque',
        image: '/episodes/env-retail.jpg',
      },
    ],
  },

  {
    id: 'ep-04',
    slug: 'groupe-lavaux',
    aliases: ['lavaux'],
    episodeNumber: 4,
    title: 'Un catalogue de 90 000 références et personne pour le lire',
    excerpt:
      'Yannick Dorval a passé trois ans à digitaliser un distributeur B2B. Il raconte le vrai chantier : convaincre 340 commerciaux que l’outil ne les remplace pas.',
    description: [
      'Le Groupe Lavaux distribue des fournitures techniques à 12 000 clients professionnels. Sur le papier, le projet était un e-commerce. Dans les faits, c’était une négociation sociale de trois ans.',
      'Enregistré au siège, dans une salle de réunion vitrée qui donne sur le plateau commercial. Yannick Dorval démonte l’idée que la digitalisation d’un distributeur est un sujet technique.',
      'Il détaille ce qui a débloqué la situation : arrêter de parler de « transformation digitale » et commencer à parler de commission.',
    ],
    publishedAt: '2026-06-17',
    duration: 3105,
    recordedAt: 'Villeurbanne, Rhône',
    topics: ['Digital', 'Distribution'],
    guest: {
      name: 'Yannick Dorval',
      role: 'Directeur digital',
      company: 'Groupe Lavaux',
      bio: 'Douze ans en distribution spécialisée avant de prendre la direction digitale du Groupe Lavaux en 2022. Il pilote la plateforme e-commerce et la refonte du parcours commercial.',
      linkedin: 'https://www.linkedin.com/',
      website: 'https://www.groupe-lavaux.fr',
      portrait: {
        src: '/episodes/groupe-lavaux-portrait.jpg',
        alt: 'Yannick Dorval, directeur digital du Groupe Lavaux, devant le siège de Villeurbanne.',
        width: 1400,
        height: 1750,
      },
    },
    coverImage: {
      src: '/episodes/groupe-lavaux-portrait.jpg',
      alt: 'Yannick Dorval, directeur digital du Groupe Lavaux, devant le siège de Villeurbanne.',
      width: 1400,
      height: 1750,
    },
    environmentImage: {
      src: '/episodes/env-siege.jpg',
      alt: 'Hall et plateau commercial du siège du Groupe Lavaux à Villeurbanne.',
      width: 1800,
      height: 1200,
    },
    audioUrl: AUDIO,
    audioBytes: 1280044,
    youtubeId: 'dQw4w9WgXcQ',
    clientUrl: 'https://www.groupe-lavaux.fr',
    platforms: {
      spotify: 'https://open.spotify.com/show/derriere-la-marque',
      apple: 'https://podcasts.apple.com/fr/podcast/derriere-la-marque',
      youtube: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      deezer: 'https://www.deezer.com/fr/show/derriere-la-marque',
    },
    resources: [
      {
        title: 'Bilan du e-commerce B2B en France',
        url: 'https://www.fevad.com/',
        category: 'Étude',
        source: 'Fevad',
      },
      {
        title: 'Recommandations de la CNIL sur les données clients',
        url: 'https://www.cnil.fr/',
        category: 'Référence',
        source: 'CNIL',
      },
      {
        title: 'L’Usine Digitale — transformation des distributeurs',
        url: 'https://www.usine-digitale.fr/',
        category: 'Article',
        source: 'L’Usine Digitale',
      },
      {
        title: 'Groupe Lavaux',
        url: 'https://www.groupe-lavaux.fr',
        category: 'Entreprise',
        source: 'Site du client',
      },
    ],
  },

  {
    id: 'ep-05',
    slug: 'orbis-mobility',
    aliases: ['orbis'],
    episodeNumber: 5,
    title: 'Lever moins pour décider plus',
    excerpt:
      'Thomas Kerguelen a refusé une série B. Deux ans plus tard, Orbis Mobility est rentable et opère dans neuf villes.',
    description: [
      'Orbis Mobility conçoit des micro-véhicules utilitaires pour la logistique urbaine. En 2024, l’entreprise avait une term sheet de 22 millions sur la table. Elle ne l’a pas signée.',
      'Enregistré sur le toit du bâtiment que l’équipe partage avec son atelier de prototypage. Thomas Kerguelen explique la décision sans mysticisme : ce que la levée aurait imposé en rythme de déploiement, et pourquoi ce rythme aurait cassé le produit.',
      'Un épisode utile à toute personne qui confond croissance et vitesse — et qui parle aussi, très concrètement, de ce que ça coûte de dire non.',
    ],
    publishedAt: '2026-07-15',
    duration: 2874,
    recordedAt: 'Nantes, Loire-Atlantique',
    topics: ['Entrepreneuriat', 'Innovation'],
    guest: {
      name: 'Thomas Kerguelen',
      role: 'Co-fondateur',
      company: 'Orbis Mobility',
      bio: 'Ingénieur mécanique, il co-fonde Orbis Mobility en 2020 après cinq ans chez un constructeur. L’entreprise compte 46 personnes et opère dans neuf villes européennes.',
      linkedin: 'https://www.linkedin.com/',
      website: 'https://www.orbis-mobility.com',
      portrait: {
        src: '/episodes/orbis-mobility-portrait.jpg',
        alt: 'Thomas Kerguelen, co-fondateur d’Orbis Mobility, sur le toit de l’atelier nantais.',
        width: 1400,
        height: 1750,
      },
    },
    coverImage: {
      src: '/episodes/orbis-mobility-portrait.jpg',
      alt: 'Thomas Kerguelen, co-fondateur d’Orbis Mobility, sur le toit de l’atelier nantais.',
      width: 1400,
      height: 1750,
    },
    environmentImage: {
      src: '/episodes/env-atelier.jpg',
      alt: 'Atelier de prototypage d’Orbis Mobility à Nantes.',
      width: 1800,
      height: 1200,
    },
    audioUrl: AUDIO,
    audioBytes: 1280044,
    youtubeId: 'dQw4w9WgXcQ',
    clientUrl: 'https://www.orbis-mobility.com',
    platforms: {
      spotify: 'https://open.spotify.com/show/derriere-la-marque',
      apple: 'https://podcasts.apple.com/fr/podcast/derriere-la-marque',
      youtube: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      deezer: 'https://www.deezer.com/fr/show/derriere-la-marque',
      amazon: 'https://music.amazon.fr/podcasts/derriere-la-marque',
    },
    resources: [
      {
        title: 'Logistique urbaine — état des lieux et scénarios',
        url: 'https://www.ademe.fr/',
        category: 'Étude',
        source: 'ADEME',
      },
      {
        title: 'Bpifrance — financement de l’innovation',
        url: 'https://www.bpifrance.fr/',
        category: 'Référence',
        source: 'Bpifrance',
      },
      {
        title: 'Dezeen — design et architecture',
        url: 'https://www.dezeen.com/',
        category: 'Design',
        source: 'Dezeen',
        description: 'La veille que Thomas cite quand il parle du dessin des véhicules.',
      },
      {
        title: 'Orbis Mobility',
        url: 'https://www.orbis-mobility.com',
        category: 'Entreprise',
        source: 'Site du client',
      },
    ],
  },

  {
    id: 'ep-06',
    slug: 'nord-cosmetics',
    aliases: ['nord'],
    episodeNumber: 6,
    title: 'Une marque n’est pas un territoire de communication',
    excerpt:
      'Léa Marchetti a supprimé la charte de marque de Nord Cosmetics pour la remplacer par onze règles. Elle explique pourquoi les chartes ne tiennent plus.',
    description: [
      'Nord Cosmetics produit 60 références et publie environ 400 contenus par mois sur sept marchés. La charte de marque faisait 96 pages. Personne ne l’ouvrait.',
      'Léa Marchetti l’a remplacée par onze règles, tenables sur une page, dont trois interdictions. Nous avons enregistré dans le laboratoire d’application, au milieu des essais teintes.',
      'Elle décrit ce que ça change opérationnellement, ce que ça a déclenché chez les équipes locales, et ce qu’elle a perdu au passage — parce qu’il y a une perte, et elle l’assume.',
    ],
    publishedAt: '2026-08-19',
    duration: 3352,
    recordedAt: 'Roubaix, Nord',
    topics: ['Marque', 'Culture'],
    guest: {
      name: 'Léa Marchetti',
      role: 'Directrice de la marque',
      company: 'Nord Cosmetics',
      bio: 'Après dix ans en agence, elle rejoint Nord Cosmetics en 2021 pour prendre la direction de la marque. Elle y a conduit la refonte de la plateforme et du dispositif de contenu sur sept marchés.',
      linkedin: 'https://www.linkedin.com/',
      website: 'https://www.nord-cosmetics.com',
      portrait: {
        src: '/episodes/nord-cosmetics-portrait.jpg',
        alt: 'Léa Marchetti, directrice de la marque de Nord Cosmetics, dans le laboratoire d’application de Roubaix.',
        width: 1400,
        height: 1750,
      },
    },
    coverImage: {
      src: '/episodes/nord-cosmetics-portrait.jpg',
      alt: 'Léa Marchetti, directrice de la marque de Nord Cosmetics, dans le laboratoire d’application de Roubaix.',
      width: 1400,
      height: 1750,
    },
    environmentImage: {
      src: '/episodes/env-studio.jpg',
      alt: 'Deux fauteuils et deux micros face à face devant un mur de tasseaux de bois, sous une lumière chaude.',
      width: 2752,
      height: 1536,
    },
    audioUrl: AUDIO,
    audioBytes: 1280044,
    youtubeId: 'dQw4w9WgXcQ',
    clientUrl: 'https://www.nord-cosmetics.com',
    platforms: {
      spotify: 'https://open.spotify.com/show/derriere-la-marque',
      apple: 'https://podcasts.apple.com/fr/podcast/derriere-la-marque',
      youtube: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      deezer: 'https://www.deezer.com/fr/show/derriere-la-marque',
      amazon: 'https://music.amazon.fr/podcasts/derriere-la-marque',
      castbox: 'https://castbox.fm/channel/derriere-la-marque',
    },
    resources: [
      {
        title: 'FEBEA — le marché français de la cosmétique',
        url: 'https://www.febea.fr/',
        category: 'Étude',
        source: 'FEBEA',
      },
      {
        title: 'Cosmetic Valley',
        url: 'https://www.cosmetic-valley.com/',
        category: 'Référence',
        source: 'Cosmetic Valley',
      },
      {
        title: 'La Réclame — actualité de la création publicitaire',
        url: 'https://lareclame.fr/',
        category: 'Article',
        source: 'La Réclame',
      },
      {
        title: 'Stratégies — marques et communication',
        url: 'https://www.strategies.fr/',
        category: 'Article',
        source: 'Stratégies',
        description: 'Le dossier sur les plateformes de marque dont Léa parle en fin d’épisode.',
      },
      {
        title: 'Nord Cosmetics',
        url: 'https://www.nord-cosmetics.com',
        category: 'Entreprise',
        source: 'Site du client',
      },
      {
        title: 'Le laboratoire d’application, pendant l’enregistrement',
        url: 'https://www.youtube.com/@derrierelamarque',
        category: 'Coulisses',
        source: 'Derrière la marque',
        image: '/episodes/micro-noir.jpg',
      },
    ],
  },
];
